### ISSUE TITLE
Connection Explorer throws errors

### ISSUE THREAD

**Issue by rjoelnorgren** [ultram4rine/sqltools-clickhouse-driver#459]
Queries work fine, but any attempt to introspect the database using the SQLTools commands or the explorer pane throw:

```
[1692149547356] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1692149547356] INFO  (ls): REQUEST RECEIVED => connection/RunCommandRequest
[1692149547532] ERROR (TypeError):
    TypeError: Cannot read properties of undefined (reading 'total')
        at ti.<anonymous> (/Users/robinnorgren/.vscode/extensions/ultram4rine.sqltools-clickhouse-driver-0.4.1/out/ls/plugin.js:120:17311)
        at Generator.next (<anonymous>)
        at a (/Users/robinnorgren/.vscode/extensions/ultram4rine.sqltools-clickhouse-driver-0.4.1/out/ls/plugin.js:120:15838)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[1692149547533] ERROR (ext): ERROR: Execute query error Cannot read properties of undefined (reading 'total'), 'Cannot read properties of undefined (reading 'total')'
    ns: "error-handler"
[1692149547533] ERROR (ext): ERROR: Error while showing table records Cannot read properties of undefined (reading 'total'), {"code":-1,"data":{"driver":"ClickHouse","driverOptions":{}}}
    ns: "error-handler"
```

clickhouse server version: 23.7.2.25

**Comment by ultram4rine** [comment]
Hi @rjoelnorgren , I guess you talk about `Show all records` and `describe` table ij context menu. If i am correct, it will be fixed by #465 and released with v0.4.2 in the near future.
